apiVersion: v1
kind: Pod
metadata:
  name: webserver
  labels:
    engine: nginx
spec:
  containers:
    - name: nginx
      image: nginx:latest
      ports:
        - name: http
          containerPort: 80
          protocol: TCP
      resources:
        requests:
          cpu: "200m"
          memory: "512Mi"
        limits:
          cpu: "500m"
          memory: "1024Mi"
      volumeMounts:
        - name: "nginx-vol"
          mountPath: /usr/share/nginx/html
          readOnly: true

    - name: fortune
      image: luksa/fortune
      resources:
        requests:
          cpu: "200m"
          memory: "512Mi"
        limits:
          cpu: "500m"
          memory: "1024Mi"
      volumeMounts:
        - name: "nginx-vol"
          mountPath: /var/htdocs

  volumes:
    - name: "nginx-vol"
      emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: nginxsvc
spec:
  selector:
    engine: nginx
  ports:
    - port: 80
      targetPort: 80
      name: http
      nodePort: 30001
  type: NodePort