apiVersion: v1
kind: Pod
metadata:
  name: nginx-git
  labels:
    engine: nginx-git
spec:
  containers:
    - name: nginx-git
      image: nginx:latest
      ports:
        - name: http
          containerPort: 80
          protocol: TCP
      volumeMounts:
        - name: gitrepo
          mountPath: /usr/share/nginx/html
  volumes:
    - name: gitrepo
      gitRepo:
        repository: https://github.com/madusanka90/kubia-website-example.git
        revision: master
        directory: .