apiVersion: v1
kind: Pod
metadata:
  name: httpd
spec:
  containers:
    - name: httpd
      image: httpd:latest
      ports:
        - containerPort: 80
          name: http
          protocol: TCP
      volumeMounts:
        - name:  httpd-data
          mountPath:  /usr/local/apache2/htdocs
  volumes:
    - name: httpd-data
      persistentVolumeClaim:
        claimName: httpd