apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnly
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: retain
  hostPath:
    path: /mnt/mysql-data