apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    version: latest
    engine: nginx
spec:
  containers:
    - name: nginx
      image: nginx:latest
      ports:
        - containerPort: 80
          name: http
          protocol: TCP
      livenessProbe:
        httpGet:
          path: /
          port: 80
        initialDelaySeconds: 10
        timeoutSeconds: 1
        periodSeconds: 5
        failureThreshold: 3
      resources:
        requests:
          cpu: "200m"
          memory: "512Mi"
        limits:
          cpu: "500m"
          memory: "1024Mi"
      volumeMounts:
        - name: nginx-vol
          mountPath: /usr/share/nginx/html
  volumes:
    - name: nginx-vol
      persistentVolumeClaim:
        claimName: nginx-pvc
