apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: cronjob2
spec:
  schedule: "0,15,30,45 * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          name: cronjob2
          labels:
            version: v1
        spec:
          containers:
            - name: cronjob2
              image: luksa/batch-job  
          restartPolicy: OnFailure