apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx
spec:
  replicas: 3
  minReadySeconds: 10
  selector:
    matchLabels:
      version: "v1"
      tier: frontend
    matchExpression:
      - {key: version, operator: In, value: [v1, v2, v3]}
  template:
    metadata:
      name: nginx
      labels:
        version: "v1"
        tier: frontend
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          env:
            - name: "APP_NAME"
              value: "myweb"
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          livenessProbe:
            httpGet:
              port: 80
              path: /
            initialDelaySeconds: 10
            timeoutSeconds: 1
            periodSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              port: 80
              path: /
            initialDelaySeconds: 10
            timeoutSeconds: 1
            periodSeconds: 5
            failureThereshold: 3
          volumeMounts:
            - name: "nginx-vol"
              mountPath: "/etc/nginx/html"
      volumes:
        - name: "nginx-vol"
          hostPath:
            path: "/mnt/ngnix-data"