apiVersion: batch/v1
kind: Job
metadata:
  name: busyjob
spec:
  template:
    metadata:
      name: busybox
      labels:
        app: busybox
        version: v1
    spec:
      containers:
        - name: busybox
          image: busybox:latest
          command:
           - echo
            - "Job Completed"
      restartPolicy: OnFailure
  