apiVersion: v1
kind: ReplicationController
metadata:
  name: httpd
spec:
  replicas: 3
  selector:
    tier: frontend
    version: v1
  template:
    metadata:
      name: httpd
      labels:
        tier: frontend
        version: v1
    spec:
      containers:
        - name: httpd
          image: httpd:latest
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
          resources:
            requests:
              cpu: "200m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1024Mi"
          env:
            - name: APACHE_HOME
              value: "/usr/local/apache2"
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            timeoutSeconds: 1
            periodSeconds: 5
            failureThreshold: 3
          readinessProbe:
            exec:
              command:
                - cat
                - /usr/local/apache2/htdocs/index.html
            initialDelaySeconds: 10
            timeoutSeconds: 1
            periodSeconds: 5
            failureThreshold: 3