apiVersion: v1
kind: Service
metadata:
  name: svcci
spec:
  selector:
    app: nginx:v1
    tier: frontend
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      name: svcci
  clusterIp: None
---
apiVersion: v1
kind: Service
metadata:
  name: svcnp
spec:
  selector:
    app: nginx
    tier: frontend
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      name: http
      nodePort: 30001
---
apiVersion: v1
kind: Service
metadata:
  name: svclb
spec:
  selector:
    app: nginx
    tier: frontend
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      name: http
  loadBalancerIP: 192.168.8.168
  clusterIP: 10.140.1.40
status:
  loadBalancer:
    ingress:
      - ip: 10.138.24.14
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: svcin
spec:
  rules:
    - host: myweb.example.com
      http:
        paths:
          - path: /
            backend:
              serviceName: svcci
              servicePort: 80
          - path: /
            backend:
              serviceName: svcci_2
              servicePort: 80
    - host: myweb2.example.com
      http:
        paths:
          - path: /
            backend:
              serviceName: svcnewci
              servicePort: 80