apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: miniproj
  labels:
    role: db
    teir: backend
spec:
  selector:
    role: db
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
