apiVersion: v1
kind: Service
metadata:
  name: result
  namespace: miniproj
  labels:
    role: result
spec:
  selector:
    role: result
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30100
  

component: nexclipperlight