apiVersion: v1
kind: Service
metadata:
  name: vote
  namespace: miniproj
  labels:
    role: vote
spec:
  selector:
    role: vote
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30001