apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: httpd
spec:
  rules:
    - host: mywebserver.example.com
      http:
        paths:
          - path: /
            backend:
              serviceName: httpd
              servicePort: 80
                
          