apiVersion: v1
kind: Service
metadata:
  name: mysqlsvc
spec:
  selector:
    version: v5.6
    database: mysql
  ports:
    - name: mysql
      port: 3306
      targetPort: 3306
  type: LoadBalancer
  sessionAffinity: None
  externalLoadBalancer: local