apiVersion: v1
kind: Service
metadata:
  name: mysqlsvc
spec:
  selector:
    cersion: v5.6
    database: mysql
  ports:
    - name: mysql
      port: 3306
      targetPort: 3306
  type: ClusterIP
  clusterIP: None #headless services