apiVersion: v1
kind: Ingress
metadata:
  name: mysqlsvc
spec:
  rules:
    - host: mysql.example.com
      http:
        paths:
          - path: /
            backend:
              serviceName: mysqlsvc
              servicePort: 3306