apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  selector:
    version: latest
    engine: nginx
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30002
  type: NodePort