apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  selector:
    version: latest
    engine: nginx
  ports:
    - port: 80
      targetPort: 80
      name: http
  type: LoadBalancer
  sessionAffinity: None
  externalTrafficPolicy: Local