apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: tomcat
spec:
  rules:
    - host: myapp.example.com
      http:
        paths:
          - path: /
            backend:
              serviceName: tomcat
              servicePort: 80