apiVersion: v1
kind: Service
metadata:
  name: tomcat
spec:
  selector:
   version: latest
   tier: backend
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30003
      name: http
  type: NodePort