apiVersion: v1
kind: Service
metadata:
  name: tomcat
spec:
  selector:
    version: latest
    tier: backend
  ports:
    - port: 80
      targetPort: 8080
      name: http
  type: LoadBalancer
  sessionAffinity: None
  externalTrafficPolicy: Local