apiVersion: v1
kind: Namespace
metadata:
  name: httpd
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: apacheweb
  namespace: httpd
spec:
  replicas: 3
  selector:
    version: latest
    engine: httpd
  template:
    metadata:
      name: apacheweb
      labels:
        version: latest
        engine: httpd
    spec:
      containers:
        - name: apacheweb
          image: httpd:latest
          ports:
            - containerPort: 80
              name: httpd
              protocol: TCP
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            timeoutSeconds: 1
            periodSeconds: 5
            failureThreshold: 3
          volumeMounts:
            - name: "apache-vol"
              mountPath: "/usr/local/apache2/htdocs"
    volumes:
      - name: "apache-vol"
        hostPath:
          path: "/mnt/apache-vol"