apiVersion: v1
kind: Namespace
metadata:
  name: postgresdb
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: postgres
  namespcae: postgresdb
spec:
  replicas: 2
  minReadySeconds: 10
  selector:
    version: latest
    tier: backend
  template:
    metadata:
      name: postgres
      labels:
        version: latest
        tier: backend
  spec:
    containers:
      - name: postgres
        image: postgres:latest
        ports:
          - containerPort: 5432
            name: postgres-port
            protocol: TCP
        env:
          - name: POSTGRES_PASSWORD
            value: password
        livenessProbe:
          httpGet:
            path: /
            port: 5432
          initialDelaySeconds: 10
          timeoutSeconds: 1
          periodSeconds: 5
          failureThreshold: 3
        resources:
          requests:
            cpu: "200m"
            memory: "512Mi"
          limits:
            cpu: "500m"
            memory: "1024Mi"
        volumeMounts:
          - name: postgres-data
            mountPath: "/var/lib/postgresql/data"
    volumes:
      - name: postgres-data
        hostPath:
          path: "/mnt/data"