apiVersion: batch/v1
kind: Job
metadata:
  name: myjob1
spec:
  completions: 2
  parallelism : 2
  template:
    metadata:
      name: myjob1
      labels:
        veriosn: v1
    spec:
      containers:
        - name: myjob1
          image: luksa/batch-job
      restartPolicy: OnFailure

