apiVersion: batch/v1
kind: Job
metadata:
  name: testjob3
spec:
  completion: 6
  parallelism: 2
  template:
    metadata:
      name: testjob3
      labels:
        - version: v1
          app: web
    spec:
      containers:
        - name: testjob3
          image: luksa/batch-job
      restartPloicy: OnFailure