apiVersion: v1
kind: Service
metadata:
  name: mysql-svc
spec:
  selector:
    tier: backend
    version: v5
  ports:
    - port: 3306
      targetPort: 3306
      name: mysql-port
      ClusterIP: None