apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  replicas: 1
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
    revisionHistoryLimit: 4
  selector:
    matchLabels:
      tier: backend
      version: v5
  template:
    metadata:
      name: mysql
      labels:
        tier: backend
        version: v5
    spec:
      containers:
        - name: mysql
          image: mysql:5.6
          ports:
            - containerPort: 3306
              name: mysql-port
              protocol: TCP
          resources:
            requests:
              cpu: "200m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-sec
                  key: password
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
      volume:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: mysql-pvc