apiVersion: v1
kind: PersistentVolume
metadata:
  name: wp-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadOnlyMany
    - ReadWriteOnly
  persistentVolumeReclaimPolicy: retain
  hostPath:
    path: /mnt/wp-data
