apiVersion: v1
kind: Service
metadata:
  name: mysql-svc
spec:
  selector:
    tier: frontend
    version: v4
  ports:
    - port: 80
      targetPort: 80
      name: wp
      nodePort: 30001
  type: NodePort