apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      version: v1
      tier: backend
  template:
    metadata:
      name: mysql
      labels:
        version: v1
        tier: backend
    spec:
      containers:
        - name: mysql
          image: mysql:latest
          ports:
            - containerPort:
              name: mysql-port
              protocol: TCP
      nodeSelector:
        disk: ssd    