apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: mydaemon
spec:
  selector:
    matchLabels:
      version: v1
      tier: backend
  template:
    metadata:
      name: mydaemon
      labels:
        version: v1
        tier: backend
    spec:
      containers:
        - name: mydaemon
          image: postgres:latest
          ports:
            - containerPort: 5432
              name: postgres
              protocol: TCP
          env:
            - name: POSTGRES_PASSWORD
              value: password
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            timeoutSeconds: 1
            periodSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            timeoutSeconds: 1
            periodSeconds: 5
            failureThreshold: 3
          nodeSelector:
            disk: ssd
          volumeMounts:
            - name: "postgres-data"
              mountPath: "/mnt/postgre-data"
      volumes:
        - name: "postgres-data"
          hostPath:
            path: "/mnt/postgre-data"