apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  replicas: 1
  minReadySeconds: 20
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: robotshop/rs-mysql-db:latest
        name: mysql
        ports:
        - Containerport: 3306
          name: mysql
          protocol: TCP
      restartPolicy: Always