apiVersion: v1
kind: Pod
metadata:
  name: apacheweb
  labels:
    version: latest
    engine: httpd
spec:
  containers:
    - name: apacheweb
      image: httpd:latest
      resources:
        requests:
          cpu: "500m"
          memory: "128Mi"
        limits:
          cpu: "1000m"
          memory: "256Mi"
      ports:
        - containerPort: 80
          name: http
          protocol: TCP
      volumeMounts:
        - name: "apache-vol"
          mountPath: "/usr/local/apache2/htdocs"
  volumes:
    - name: "apache-vol"
      hostPath:
        path: "/mnt/apache-vol" 