apiVersion: v1
kind: Pod
metadata:
  name: nginxweb
  labels:
    version: latest
    engine: nginx
spec:
  containers:
    - name: nginxweb
      image: nginx:latest
      resources:
        requests:
          cpu: "200m"
          memory: "128Mi"
        limits:
          cpu: "500m"
          memory: "256Mi"
      ports:
        - containerPort: 80
          protocol:  TCP
          name: http
      volumeMounts:
        - name: "nginx-vol"
          mountPath: "/usr/share/nginx/html"
  volumes:
    - name: "nginx-vol"
      hostPath:
        path: "/mnt/nginx-vol"