apiVersion: v1
kind: Pod
metadata:
  name: postgresdb
  labels:
    version: latest
    database: postgres
spec:
  containers:
    - name: postgres
      image: postgres:latest
      resources:
        requests:
          cpu: "300m"
          memory: "512Mi"
        limits:
          cpu: "500m"
          memory: "1024Mi"
      ports:
        - containerPort: 5432
          name: postgres
          protocol: TCP
      env:
        - name: POSTGRES_PASSWORD
          value: cGFzc3dvcmQK
      volumeMounts:
        - name: "postgres-vol"
          mountPath: "/var/lib/postgresql/data"
  volumes:
    - name: "postgres-vol"
      hostPath:
        path: "/mnt/postgres-vol"