apiVersion: v1
kind: Pod
metadata:
  name: tomcatweb
  labels:
    version: latest
    engine: tomcat
spec:
  containers:
    - name: tomcatweb
      image: tomcat:latest
      resources:
        requests:
          cpu: "300m"
          memory: "128Mi"
        limits:
          cpu: "500m"
          memory: "512Mi"
      ports:
        - containerPort: 8080
          protcol:  TCP
          name: http
      volumeMounts:
        - name: "tomcat-vol"
          mountPath: "/usr/local/tomcat/webapps"
  volumes:
    - name: "tomcat-vol"
      hostPath:
        path: "/mnt/tomcat-vol"