apiVersion: v1
kind: Pod
metadata:
  name: ubuntu
  labels:
    version: latest
    os: ubuntu
spec:
  containers:
    - name: ubuntu
      image: ubuntu:latest
      command: ["/bin/echo"]
      args: ["hello world"]