apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
   containers:
     - name: nginx
       image: nginx:latest
       ports:
        - containerPort: 80
          name: http
          protocol: TCP
       volumeMounts:
          - name: nginx-vol
            mountPath: /etc/nginx/conf.d
            readOnly: true
   volumes:
      - name: nginx-vol
        configMap:
          name: nginx-cm
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  selector:
    tier: frontend
  ports:
    - port: 80
      targetPort: 80
      name: nginx
      nodePort: 30001
  type: NodePort