apiVersion: v1
kind: Pod
metadata:
  name: mysql
spec:
  containers:
    - name: mysql
      image: mysql:latest
      ports:
        - containerPort: 3306
          name: mysql
          protocol: TCP
      livenessProbe:
        exec:
          command:
            - cat
            - /test.txt
        initialDelaySeconds: 10
        timeoutSeconds: 1
        periodSeconds: 20
        failureThreshold: 3
      resources:
        requests:
          cpu: "200m"
          memory: "512Mi"
        limits:
          cpu: "500m"
          memory: "1024Mi"
      env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysqlpw
              key: MYSQL_ROOT_PASSWORD
  restartPolicy: Always
            
          