apiVersion: v1
kind: Pod
metadata:
  name: postgrespod
spec:
  containers:
    - name: postgrespod
      image: postgres:latest
      ports:
        - containerPort: 5432
          name: postgres-port
          protocol: TCP
      env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgresec
              key: username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgresec
              key: password
              